// <auto-generated />
using System;
using LeaseBridge.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaseBridge.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeaseBridge.API.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__AppUsers__1788CC4C4ADB3655");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "IdentityUserId" }, "UQ_AppUsers_IdentityUserId")
                        .IsUnique()
                        .HasFilter("[IdentityUserId] IS NOT NULL");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId")
                        .HasName("PK__Applicat__C93A4C99F7AA0BFA");

                    b.HasIndex("StatusId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.ApplicationStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StatusId")
                        .HasName("PK__Applicat__C8EE206385352328");

                    b.ToTable("ApplicationStatus", (string)null);
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__6A4BEDD6B9779A51");

                    b.HasIndex("TenantId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Lease", b =>
                {
                    b.Property<int>("LeaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaseId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("LeaseId")
                        .HasName("PK__Leases__21FA58C114FB33A2");

                    b.HasIndex("StatusId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitId");

                    b.ToTable("Leases");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.LeaseStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StatusId")
                        .HasName("PK__LeaseSta__C8EE20637552008F");

                    b.HasIndex(new[] { "Name" }, "UQ_LeaseStatus_Name")
                        .IsUnique();

                    b.ToTable("LeaseStatus", (string)null);
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId")
                        .HasName("PK__Maintena__32499E7757CAB96A");

                    b.HasIndex("StaffId");

                    b.HasIndex(new[] { "RequestId", "StaffId" }, "UQ_Request_Staff")
                        .IsUnique();

                    b.ToTable("MaintenanceAssignments");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Maintena__19093A0BCD2F05BF");

                    b.HasIndex(new[] { "Name" }, "UQ_MaintenanceCategories_Name")
                        .IsUnique();

                    b.ToTable("MaintenanceCategories");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("RequestId")
                        .HasName("PK__Maintena__33A8517A6EB8F73D");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UnitId");

                    b.HasIndex(new[] { "TicketNumber" }, "UQ_Ticket")
                        .IsUnique();

                    b.HasIndex(new[] { "TicketNumber" }, "UQ__Maintena__CBED06DAB3AAE172")
                        .IsUnique();

                    b.ToTable("MaintenanceRequests");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StatusId")
                        .HasName("PK__Maintena__C8EE20636D4895EC");

                    b.HasIndex(new[] { "Name" }, "UQ_MaintenanceStatus_Name")
                        .IsUnique();

                    b.ToTable("MaintenanceStatus", (string)null);
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceUpdate", b =>
                {
                    b.Property<int>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpdateId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("UpdateId")
                        .HasName("PK__Maintena__7A0CF3C55F5D63B3");

                    b.HasIndex("RequestId");

                    b.HasIndex("StatusId");

                    b.ToTable("MaintenanceUpdates");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int?>("MaintenanceRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E1255D49916");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("MaintenanceRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<int>("LeaseId")
                        .HasColumnType("int");

                    b.Property<int>("MethodId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A3867B7C952");

                    b.HasIndex("LeaseId");

                    b.HasIndex("MethodId");

                    b.HasIndex("StatusId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.PaymentMethod", b =>
                {
                    b.Property<int>("MethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MethodId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MethodId")
                        .HasName("PK__PaymentM__FC681851F4CF137C");

                    b.HasIndex(new[] { "Name" }, "UQ_PaymentMethods_Name")
                        .IsUnique();

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.PaymentStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StatusId")
                        .HasName("PK__PaymentS__C8EE2063B7DD4DC4");

                    b.HasIndex(new[] { "Name" }, "UQ_PaymentStatus_Name")
                        .IsUnique();

                    b.ToTable("PaymentStatus", (string)null);
                });

            modelBuilder.Entity("LeaseBridge.API.Models.PriorityType", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriorityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PriorityId")
                        .HasName("PK__Priority__D0A3D0BEAE1C0E68");

                    b.HasIndex(new[] { "Name" }, "UQ_PriorityTypes_Name")
                        .IsUnique();

                    b.ToTable("PriorityTypes");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PropertyId")
                        .HasName("PK__Properti__70C9A735812141E8");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1ACDC799A5");

                    b.HasIndex(new[] { "Name" }, "UQ_Roles_Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.StaffSkill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("SkillId")
                        .HasName("PK__StaffSki__DFA09187A563FF8B");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "StaffId", "CategoryId" }, "UQ_Staff_Skill")
                        .IsUnique();

                    b.ToTable("StaffSkills");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<decimal>("RentAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UnitId")
                        .HasName("PK__Units__44F5ECB524C2F27E");

                    b.HasIndex("PropertyId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.UnitStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("StatusId")
                        .HasName("PK__UnitStat__C8EE2063A09CE406");

                    b.HasIndex(new[] { "Name" }, "UQ_UnitStatus_Name")
                        .IsUnique();

                    b.ToTable("UnitStatus", (string)null);
                });

            modelBuilder.Entity("LeaseBridge.API.Models.UnitType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TypeId")
                        .HasName("PK__UnitType__516F03B52D43BEAD");

                    b.HasIndex(new[] { "Name" }, "UQ_UnitTypes_Name")
                        .IsUnique();

                    b.ToTable("UnitTypes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LeaseBridge.API.Models.AppUser", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.Role", "Role")
                        .WithMany("AppUsers")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__AppUsers__RoleId__4D94879B");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Application", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.ApplicationStatus", "Status")
                        .WithMany("Applications")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Applicati__Statu__534D60F1");

                    b.HasOne("LeaseBridge.API.Models.AppUser", "Tenant")
                        .WithMany("Applications")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK__Applicati__Tenan__5165187F");

                    b.HasOne("LeaseBridge.API.Models.Unit", "Unit")
                        .WithMany("Applications")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK__Applicati__UnitI__52593CB8");

                    b.Navigation("Status");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Feedback", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.AppUser", "Tenant")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK__Feedback__Tenant__6754599E");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Lease", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.LeaseStatus", "Status")
                        .WithMany("Leases")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Leases__StatusId__5629CD9C");

                    b.HasOne("LeaseBridge.API.Models.AppUser", "Tenant")
                        .WithMany("Leases")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK__Leases__TenantId__5441852A");

                    b.HasOne("LeaseBridge.API.Models.Unit", "Unit")
                        .WithMany("Leases")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK__Leases__UnitId__5535A963");

                    b.Navigation("Status");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceAssignment", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.MaintenanceRequest", "Request")
                        .WithMany("MaintenanceAssignments")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Reque__5DCAEF64");

                    b.HasOne("LeaseBridge.API.Models.AppUser", "Staff")
                        .WithMany("MaintenanceAssignments")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Staff__5EBF139D");

                    b.Navigation("Request");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceRequest", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.MaintenanceCategory", "Category")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Categ__59063A47");

                    b.HasOne("LeaseBridge.API.Models.PriorityType", "Priority")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("PriorityId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Prior__59FA5E80");

                    b.HasOne("LeaseBridge.API.Models.MaintenanceStatus", "Status")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Statu__5AEE82B9");

                    b.HasOne("LeaseBridge.API.Models.AppUser", "Tenant")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Tenan__571DF1D5");

                    b.HasOne("LeaseBridge.API.Models.Unit", "Unit")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__UnitI__5812160E");

                    b.Navigation("Category");

                    b.Navigation("Priority");

                    b.Navigation("Status");

                    b.Navigation("Tenant");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceUpdate", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.MaintenanceRequest", "Request")
                        .WithMany("MaintenanceUpdates")
                        .HasForeignKey("RequestId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Reque__5BE2A6F2");

                    b.HasOne("LeaseBridge.API.Models.MaintenanceStatus", "Status")
                        .WithMany("MaintenanceUpdates")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__Statu__5CD6CB2B");

                    b.Navigation("Request");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Notification", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.Application", "Application")
                        .WithMany("Notifications")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("FK__Notificat__Appli__66603565");

                    b.HasOne("LeaseBridge.API.Models.MaintenanceRequest", "MaintenanceRequest")
                        .WithMany("Notifications")
                        .HasForeignKey("MaintenanceRequestId")
                        .HasConstraintName("FK__Notificat__Maint__656C112C");

                    b.HasOne("LeaseBridge.API.Models.AppUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__6477ECF3");

                    b.Navigation("Application");

                    b.Navigation("MaintenanceRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Payment", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.Lease", "Lease")
                        .WithMany("Payments")
                        .HasForeignKey("LeaseId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__LeaseI__619B8048");

                    b.HasOne("LeaseBridge.API.Models.PaymentMethod", "Method")
                        .WithMany("Payments")
                        .HasForeignKey("MethodId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__Method__628FA481");

                    b.HasOne("LeaseBridge.API.Models.PaymentStatus", "Status")
                        .WithMany("Payments")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__Status__6383C8BA");

                    b.Navigation("Lease");

                    b.Navigation("Method");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.StaffSkill", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.MaintenanceCategory", "Category")
                        .WithMany("StaffSkills")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__StaffSkil__Categ__60A75C0F");

                    b.HasOne("LeaseBridge.API.Models.AppUser", "Staff")
                        .WithMany("StaffSkills")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK__StaffSkil__Staff__5FB337D6");

                    b.Navigation("Category");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Unit", b =>
                {
                    b.HasOne("LeaseBridge.API.Models.Property", "Property")
                        .WithMany("Units")
                        .HasForeignKey("PropertyId")
                        .IsRequired()
                        .HasConstraintName("FK__Units__PropertyI__4E88ABD4");

                    b.HasOne("LeaseBridge.API.Models.UnitStatus", "Status")
                        .WithMany("Units")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__Units__StatusId__5070F446");

                    b.HasOne("LeaseBridge.API.Models.UnitType", "Type")
                        .WithMany("Units")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Units__TypeId__4F7CD00D");

                    b.Navigation("Property");

                    b.Navigation("Status");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeaseBridge.API.Models.AppUser", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Feedbacks");

                    b.Navigation("Leases");

                    b.Navigation("MaintenanceAssignments");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("Notifications");

                    b.Navigation("StaffSkills");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Application", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.ApplicationStatus", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Lease", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.LeaseStatus", b =>
                {
                    b.Navigation("Leases");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceCategory", b =>
                {
                    b.Navigation("MaintenanceRequests");

                    b.Navigation("StaffSkills");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceRequest", b =>
                {
                    b.Navigation("MaintenanceAssignments");

                    b.Navigation("MaintenanceUpdates");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.MaintenanceStatus", b =>
                {
                    b.Navigation("MaintenanceRequests");

                    b.Navigation("MaintenanceUpdates");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.PriorityType", b =>
                {
                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Property", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Role", b =>
                {
                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.Unit", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Leases");

                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.UnitStatus", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("LeaseBridge.API.Models.UnitType", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
